function init_gc14ed3c8(container) {
const size=4;let board,score,best=0,over=false,moved=false;const colors={};const scoreEl=document.createElement('div');const boardEl=document.createElement('div');const overEl=document.createElement('div');let gridEl;
function initUI(){container.innerHTML='';const wrap=document.createElement('div');wrap.className='g2048-wrap';const head=document.createElement('div');head.className='g2048-head';const scores=document.createElement('div');scores.className='g2048-scores';scoreEl.className='g2048-box';scoreEl.innerHTML='<div class="lab">得分</div><div class="val" id="g2048-score">0</div>';const bestBox=document.createElement('div');bestBox.className='g2048-box';bestBox.innerHTML='<div class="lab">最高</div><div class="val" id="g2048-best">0</div>';scores.appendChild(scoreEl);scores.appendChild(bestBox);const btn=document.createElement('button');btn.className='g2048-btn';btn.textContent='重来';btn.addEventListener('click',reset);head.appendChild(scores);head.appendChild(btn);boardEl.className='g2048-board';gridEl=document.createElement('div');gridEl.className='g2048-grid';boardEl.appendChild(gridEl);overEl.className='g2048-over';boardEl.appendChild(overEl);const hint=document.createElement('div');hint.className='g2048-hint';hint.textContent='使用方向键或 WASD 移动方块，相同数字合并，目标合成 2048！';wrap.appendChild(head);wrap.appendChild(boardEl);wrap.appendChild(hint);container.appendChild(wrap);}
function reset(){board=[];for(let i=0;i<size;i++){board.push(new Array(size).fill(0))}score=0;over=false;addTile();addTile();render();}
function addTile(){const empty=[];for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(board[r][c]===0)empty.push([r,c]);if(empty.length===0)return;const idx=Math.floor(Math.random()*empty.length);const[r,c]=empty[idx];board[r][c]=Math.random()<0.9?2:4;}
function render(){gridEl.innerHTML='';for(let r=0;r<size;r++){for(let c=0;c<size;c++){const val=board[r][c];const cell=document.createElement('div');cell.className='g2048-cell';if(val>0){cell.dataset.v=val;cell.textContent=val}gridEl.appendChild(cell)}}document.getElementById('g2048-best').textContent=best;document.getElementById('g2048-score').textContent=score;}
function slide(row){const arr=row.filter(v=>v);for(let i=0;i<arr.length-1;i++){if(arr[i]===arr[i+1]){arr[i]*=2;score+=arr[i];arr.splice(i+1,1)}}while(arr.length<size)arr.push(0);return arr;}
function move(dir){if(over)return;let rotated=board.map(r=>r.slice());const before=JSON.stringify(rotated);if(dir==='left'){rotated=rotated.map(slide)}else if(dir==='right'){rotated=rotated.map(r=>slide(r.slice().reverse()).reverse())}else if(dir==='up'){for(let c=0;c<size;c++){const col=[];for(let r=0;r<size;r++)col.push(rotated[r][c]);const res=slide(col);for(let r=0;r<size;r++)rotated[r][c]=res[r]}}else if(dir==='down'){for(let c=0;c<size;c++){const col=[];for(let r=0;r<size;r++)col.push(rotated[r][c]);const res=slide(col.reverse()).reverse();for(let r=0;r<size;r++)rotated[r][c]=res[r]}}const after=JSON.stringify(rotated);if(before!==after){board=rotated;addTile();if(score>best)best=score;if(!canMove()){over=true;showOver()}render()}}
function canMove(){for(let r=0;r<size;r++)for(let c=0;c<size;c++){if(board[r][c]===0)return true;if(c<size-1&&board[r][c]===board[r][c+1])return true;if(r<size-1&&board[r][c]===board[r+1][c])return true}return false}
function showOver(){overEl.innerHTML='';const msg=document.createElement('div');msg.className='msg';msg.textContent='游戏结束';const sub=document.createElement('div');sub.className='sub';sub.textContent='得分：'+score;const btn=document.createElement('button');btn.className='g2048-btn';btn.textContent='再来一局';btn.addEventListener('click',reset);overEl.appendChild(msg);overEl.appendChild(sub);overEl.appendChild(btn);overEl.classList.add('show');}
function keyHandler(e){const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();if(k==='arrowleft'||k==='a')move('left');else if(k==='arrowright'||k==='d')move('right');else if(k==='arrowup'||k==='w')move('up');else if(k==='arrowdown'||k==='s')move('down')}}
container.addEventListener('keydown',keyHandler);container.tabIndex=0;let startX=0,startY=0;boardEl.addEventListener('touchstart',e=>{startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});boardEl.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-startX;const dy=e.changedTouches[0].clientY-startY;if(Math.abs(dx)<30&&Math.abs(dy)<30)return;if(Math.abs(dx)>Math.abs(dy)){move(dx>0?'right':'left')}else{move(dy>0?'down':'up')}},{passive:true});initUI();reset();container.focus();
return function cleanup(){container.removeEventListener('keydown',keyHandler)}}
}